### ISSUE TITLE
Errors when the pinyin of the hanzi has spaces in between

### ISSUE THREAD

**Issue by NRY0927** [vonpetersenn/Pleco-to-Anki#10]
I recently tried to make custom cards and used a software to create the pinyin from hanzi, and copied into pleco. Importing using the addon creates an error, and after some debugging, found out the issue was because of the spaces. Once I removed the spaces from the txt file, it worked. Possibly could update to remove spaces to the pinyin as well?

**Comment by vonpetersenn** [comment]
I'm not sure I quite understand how you run into this problem. Is the pinyin not being exported together with the other fields from Pleco?

**Comment by NRY0927** [comment]
This problem only occurs on custom cards, where for the pronunciation if
you put a space there will be one in the txt which breaks the import and
only imports some

**Comment by vonpetersenn** [comment]
Ok I understand. 
I will probably add some code in the module that processes the Pinyin to get rid of any whitespaces before further processing.

Your usecase of custom pleco notes that you then import to Anki via an addon seems a bit complex to me. Have you thought about making your notes in a spreadsheet and to import the spreadsheet to Anki? There are tools out there that can help to  automatically add a column for pinyin, a column with a machine translation etc.

**Comment by NRY0927** [comment]
What I basically did for the custom pleco notes was that there are specific words and phrases in Chinese not found in pleco, and pleco gives us a feature to create a custom card including definition. I don't really use excel or sheets often, and I lack the experience to deal with other stuff, and this addon seems more reliable to me than my own skills 😅 But good suggestion, I'll check it out

**Comment by vonpetersenn** [comment]
I can not reproduce your problem. When I import pleco bookmarks that I manipulate before by adding white spaces, it runs without error.
