### ISSUE TITLE
Not Able to Import Audio from Pleco

### ISSUE THREAD

**Issue by mreiter01** [vonpetersenn/Pleco-to-Anki#15]
Hi!

First, I want to thank you for this incredibly useful program. I am hoping you can help me resolve this issue!

I have been unable to find a way to automatically import audio from Pleco to Anki. I have the Spoonfed add-on, but it does not have examples or audio for the vast majority of the words I study. It is too time-consuming for me to manually record every pronunciation and example sentence. 

Are there any setting configurations I can change so that audio is directly imported? I have tried turning the bulk-add audio on and off, but it made no difference. 

Thank you!

**Comment by vonpetersenn** [comment]
Hello,

I am glad that you find the add-on useful :)

The AddOn does not support to automatically add audio files apart from the Spoonfed examples.

I suggest that you try out the add-on `AwesomeTTS` for adding audio files in bulks. 
In particular, you can obtain a free API-key and add A.I. generated voice files. I personally made a Microsoft Azure account to get an API key for "SpeechServices".
