### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by ghost** [vonpetersenn/Pleco-to-Anki#4]
Hi, really excited to use this! I just downloaded and I'm getting:

Debug info:
Anki 2.1.66 (70506aeb) Python 3.9.15 Qt 6.5.2 PyQt 6.5.2
Platform: Windows-10-10.0.19041
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-10-02 10:15:25
Add-ons possibly involved: ⁨Pleco to Anki⁩

Caught exception:
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\pleco_to_anki\__init__.py", line 48, in excecuted_function
    all_bookmarks = All_Bookmarks(configs.file_name)
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\pleco_to_anki\pleco\All_Bookmarks.py", line 5, in __init__
    self.raw_data = delete_category_headings(self.raw_data)
NameError: name 'delete_category_headings' is not defined

Any idea what I can do to fix?

**Comment by vonpetersenn** [comment]
Are you using version 1.0.1 or 1.0.0?
I think I might have made an error in version 1.0.1 that is causing the issue.
I will have a better look at it later and give more info.

**Comment by ghost** [comment]
This is on 1.0.1

**Comment by vonpetersenn** [comment]
The error should be resolved in the newest version, that I just uploaded. Please uninstall in install again and let me know if it works now. Thanks.

**Comment by ghost** [comment]
It's working perfectly now! Thanks a ton.
