### ISSUE TITLE
Configuration Issue PR -- fixed

### ISSUE THREAD

**Issue by BZhaoo** [vonpetersenn/Pleco-to-Anki#5]
After trying to load up the specific .txt Pleco Export file into Anki, I am left with a specific error that read as so. Clearly, has something to do with the configuration and GUI. Currently, I'm unable to use the plug-in as intended because of this error.

"Error
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨Pleco to Anki⁩':
⁨Traceback (most recent call last):
  File "aqt.addons", line 246, in loadAddons
  File "/Users/UserName/Library/Application Support/Anki2/addons21/427686509/__init__.py", line 8, in <module>
    from .ImportBookmarksGUI import ImportBookmarksGUI
  File "/Users/UserName/Library/Application Support/Anki2/addons21/427686509/ImportBookmarksGUI.py", line 8, in <module>
    from pleco_to_anki.Configuration import Configuration
ModuleNotFoundError: No module named 'pleco_to_anki'"

What's interesting is when you go on to click and load up the add-in via the Anki tools section, the configuration button is null and nonclickable.

**Comment by vonpetersenn** [comment]
Hello, 
I will have a look at the problem. Let me just ask you, how did you install the add-on?
Through the .ankiaddon file, by copying the pleco_to_anki folder, or through Ankiweb?

**Comment by BZhaoo** [comment]
All good ~ appreciate you for getting back so quick. The current error is produced by downloading through AnkiWeb via the cited add-on code. I saw the prior comment that the downloading through GitHub works fine so I'll test that out in a bit.

**Comment by vonpetersenn** [comment]
Ok thank you. I thought I fixed the error that the person who wrote the comment was referring to. Apperantly, the version on AnkiWeb is still disfunctional then...
I'll try to fix that somehow.
