### ISSUE TITLE
Existing notes in the collection / duplicate tagging option appears to be broken

### ISSUE THREAD

**Issue by ethanxrosen** [vonpetersenn/Pleco-to-Anki#9]
expected behaviour
- export flashcards from pleco in a category using the settings mentioned in docs
- import into anki, they're added to 'pleco' deck
- add more flashcards in pleco later. now the category includes flashcards that have already been exported along with new ones
- using the "existing notes" option on import to anki, only the new ones are imported and none of the old

actual behaviour
- many notes which are not duplicates are tagged as duplicates, and not imported when they should have been

other info that might be relevant
- using simplified chinese
- options for reformating were all enabled, spoonfed examples was off
- checked that the duplicates weren't existing elsewhere in my anki library using the anki duplicates finding feature on the 'hanzi' field, and verified that there weren't duplicates in other decks

**Comment by vonpetersenn** [comment]
Are "duplicate" notes being imported  when you use the option "Create Note Anyway"?

I have also noticed that this feature does not work as intended. The reason is, that identifiying duplicate notes does not work the way I thought when I originally coded the add-on. I already thought about dropping the feature from the add-on.

**Comment by ethanxrosen** [comment]
Thanks for the quick response, the "create note anyway option" works as expected. Anki (desktop only?) has a built in find duplicates option which has been an OK workaround for me.

**Comment by vonpetersenn** [comment]
I thought the same. As Anki has a built in way to notify you about duplicates, I have since deleted the option from the Addon.
